name: liupangpang
bookTitle: springboot
address:
remoteServer: api.yjfzj.com
fundcps:
    hessian:
        url: ${fundcps.url}/hessian

connection:
    username: root
    password: root
server:
  port: 80

