name: liupangpang
bookTitle: springboot
address:
remoteServer: 10.10.10.6
fundcps:
    hessian:
        url: ${fundcps.url}/hessian

connection:
    username: root
    password: root
server:
  port: 80

