name: liupangpang
bookTitle: springboot
address: http://drowningfish.top
fundcps:
    hessian:
        url: ${fundcps.url}/hessian

connection:
    username: root
    password: root
server:
  port: 80

